In [ ]:
import pandas as pd

gym = pd.read_csv('gym_members.csv')

In [ ]:
#q1

print("Gymm : " , gym.shape)

In [ ]:
## monthly fee and cancel_date have missing values
print(gym.info())

In [ ]:
## monthly fee contains regex characters so for now it is of object type
gym.head()

In [ ]:
gym['plan'].value_counts(dropna = False)

In [ ]:
#q5
gym['monthly_fee'] = gym['monthly_fee'].str.replace("$", "", regex=False)
gym['monthly_fee'] = pd.to_numeric(gym['monthly_fee'] , errors = 'coerce')

In [ ]:
#q6
gym['age'] = gym['age'].replace("?", None)
gym['visits_last_month'] = gym['visits_last_month'].replace("--", None)
gym['age'] = pd.to_numeric(gym['age'], errors='coerce')
gym['visits_last_month'] = pd.to_numeric(gym['visits_last_month'], errors='coerce')

In [ ]:
#q7
gym['join_date'] = pd.to_datetime(gym['join_date'] ,format = "mixed" , dayfirst = True , errors = 'coerce')

In [ ]:
gym[["monthly_fee", "age", "visits_last_month", "join_date"]].isna().sum()

In [ ]:
#q8

## max age of a human can be 120 , it is showing 999 , similary for visits min is -ve 
gym[["age", "visits_last_month"]].describe()

In [ ]:
#Q9
gym["age"].dropna().sort_values().tail(10) # bound can be (18 , 120)
gym["visits_last_month"].dropna().sort_values().head(10) # bound will be (0 , 30)

In [28]:
#q10
gym.loc[(gym['age']) > 120 , 'age'] = None
gym.loc[(gym['age']) < 18 , 'age'] = None
gym.loc[(gym['visits_last_month']) > 30 , 'visits_last_month'] = None
gym.loc[(gym['visits_last_month']) < 0 , 'visits_last_month'] = None

In [29]:
gym[["age", "visits_last_month"]].describe()

              age  visits_last_month
count  160.000000         156.000000
mean    31.062500           8.455128
std      8.153162           4.509979
min     18.000000           0.000000
25%     25.000000           5.000000
50%     31.000000           8.000000
75%     37.000000          11.250000
max     55.000000          21.000000

In [45]:

gym['plan'].isna().count()

np.int64(174)

In [46]:
gym['gym'].value_counts(dropna = False)

gym
parramatta    48
chatswood     46
newtown       44
bondi         36
Name: count, dtype: int64

In [37]:
#Q11

gym['plan'] = gym['plan'].replace(
    {
        "STANDARD" : 'standard',
        "Chatswood"   : 'chatswood',
        "Newtown"      : 'newtown',
        "BONDI"  : 'bondi',
        "Parramatta"     : 'parramatta',
        "newtown "        :  'newtown',
        "NEWTOWN"  : 'newtown',
        "CHATSWOOD" : 'chatswood',
        "Bondi"    : 'basic',
        "Basic"    : 'basic'
    }
)

In [41]:
#q12

gym['gym'] = gym['gym'].replace(
    {
        "PARRAMATTA" : 'parramatta'
    }
)

In [47]:
#q14

#9 rows are duplicate
gym.duplicated().sum()

np.int64(9)

In [48]:
#q15
gym[gym.duplicated()]

,member_id,name,age,plan,gym,join_date,monthly_fee,visits_last_month,active,cancel_date
54,M588,Leo Walsh,21.0,None,parramatta,2023-06-04,39.0,6.0,FALSE,NaN
94,M615,Finn Mehta,40.0,standard,parramatta,2022-07-25,59.0,NaN,Yes,NaN
98,M595,Olive Mehta,31.0,standard,bondi,2023-09-17,59.0,7.0,No,2024-06-06
101,M537,Aisha Mehta,26.0,premium,parramatta,NaT,89.0,5.0,Yes,NaN
117,M536,Iris OBrien,27.0,standard,newtown,2022-01-16,59.0,6.0,Yes,NaN
132,M608,Mia Mehta,31.0,basic,parramatta,2023-09-09,39.0,9.0,Yes,NaN
134,M648,Ben Barnes,23.0,premium,chatswood,2023-12-18,89.0,7.0,No,2024-04-12
137,M538,Iris Mehta,26.0,standard,parramatta,2024-01-14,59.0,7.0,Yes,NaN
141,M513,Pia Barnes,27.0,basic,parramatta,2023-01-19,39.0,2.0,yes,2024-08-16

In [52]:
#q16
## np.int64(5)
'''gym = gym.drop_duplicates()'''
gym["member_id"].duplicated().sum()

np.int64(5)

In [50]:
#q17
gym[gym["member_id"].duplicated(keep=False)].sort_values("member_id")

,member_id,name,age,plan,gym,join_date,monthly_fee,visits_last_month,active,cancel_date
58,M515,Nikhil Costa,37.0,standard,bondi,2024-06-27,59.0,0.0,no,NaN
87,M515,Nikhil Costa,37.0,standard,bondi,2024-06-27,NaN,NaN,no,NaN
3,M521,Ryan Nguyen,36.0,standard,parramatta,2025-05-02,59.0,21.0,Yes,NaN
22,M521,Ryan Nguyen,36.0,standard,parramatta,2025-05-02,NaN,NaN,Yes,NaN
7,M553,Ella Ford,38.0,standard,parramatta,2023-06-26,59.0,12.0,Yes,NaN
148,M553,Ella Ford,38.0,standard,parramatta,2023-06-26,NaN,NaN,Yes,NaN
61,M593,Chloe Reid,24.0,premium,bondi,2022-01-25,NaN,NaN,TRUE,NaN
68,M593,Chloe Reid,24.0,premium,bondi,2022-01-25,89.0,12.0,TRUE,NaN
37,M657,Jack Shah,27.0,standard,chatswood,NaT,NaN,NaN,yes,NaN
90,M657,Jack Shah,27.0,standard,chatswood,NaT,59.0,12.0,yes,NaN